description = "Talk (hands-free: mic → transcript → answer → repeat until /talk:stop)."

prompt = """
You have tools: talk_start, talk_status, talk_stop, list_devices.

High-level behavior:
- Enter a HANDS-FREE LOOP: record → transcribe → answer → short pause → repeat.
- Keep looping until a stop condition is met.

Goal per cycle:
1) Start capture with talk_start(...).
   - Parse key=value args provided after the command. Supported keys:
     rate:int, channels:int, chunk:int, energy_gate:float, min_talk_ms:int,
     end_sil_ms:int, max_utter_ms:int, pre_roll_ms:int, device_index:int,
     blocking:bool (true/false).
   - Only pass provided args.
   - If the user asked for device listing earlier, you MAY call list_devices() once to honor a provided device_index.
2) If response.running is true AND blocking=false:
     loop:
       - sleep ~0.5s
       - call talk_status()
       - exit when running=false
3) When running=false, let T = the final transcript (from the most recent status or talk_start response).
4) If T is empty or only whitespace:
     - Briefly print a tiny status like "…listening" and count this as one idle cycle.
     - If there are 4 consecutive idle cycles (≈ no speech), END the session politely.
     - Otherwise continue to the next cycle (Step 1).
5) If T is non-empty:
     - REPLY AS THE ASSISTANT to T as if the user had typed it.
       Do NOT call more tools inside your reply. Do NOT wrap your reply in code fences.
     - After your reply has been shown, wait ~5 seconds by polling talk_status()
       (sleep ~2.5s → talk_status() → sleep ~2.5s). Do not print during this pause.
6) Before starting the next cycle, check stop conditions (below). If none, go back to Step 1.

Stop conditions (end the loop and session):
- talk_start fails or cannot start the device.
- Cumulative idle: 4 consecutive empty transcripts.
- Total wall time > 60 minutes (safety valve).
- A transcript consists solely of one of: "stop", "quit", "goodbye" (case-insensitive).
- The capture is externally stopped via /talk:stop and subsequent talk_start immediately fails.

Output rules:
- The ONLY visible text should be your assistant replies (Step 5) or brief "…listening" notices (Step 4).
- Never dump raw tool payloads, JSON, or internal state.

Notes:
- Hands-free requires blocking=false behavior from the capture tool; assume that is the default unless the user explicitly passed blocking=true.
- Keep replies concise but helpful; preserve conversational context naturally across cycles.
"""
